-- ============================================================================
-- CloudVault — Supabase Storage Bucket & Policies
-- ============================================================================
-- Configures the `user-files` storage bucket and its access policies.
--
-- Storage layout:
--   user-files/
--     <user_id>/
--       <uuid-based-filename.ext>
--
-- Access model:
--   • Each user can only interact with objects under their own <user_id>/ prefix.
--   • The path structure is enforced by matching the first path segment
--     against auth.uid()::text.
--
-- Note: These policies use Supabase's storage.objects table which has a
-- built-in `bucket_id` and `name` (the full object path) column.
-- The expression (storage.foldername(name))[1] extracts the first path
-- segment — which in our layout is always the user's UUID.
-- ============================================================================


-- ──────────────────────────────────────────────────────────────────────────
-- 1. Create the bucket (idempotent)
-- ──────────────────────────────────────────────────────────────────────────
-- Supabase doesn't have a native "create if not exists" for buckets in SQL,
-- so we use an INSERT ... ON CONFLICT to make this safe to re-run.
-- The bucket is private by default (public = false) — all access goes
-- through signed URLs generated by the backend.
-- ──────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'user-files',
  'user-files',
  false,                -- Private bucket — no anonymous access
  52428800,             -- 50 MB max file size (50 * 1024 * 1024)
  array[
    -- Images
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml',
    -- Documents
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain',
    'text/csv',
    -- Archives
    'application/zip',
    'application/x-rar-compressed',
    'application/x-7z-compressed',
    -- Media
    'video/mp4',
    'audio/mpeg'
  ]
)
on conflict (id) do update set
  file_size_limit    = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;


-- ──────────────────────────────────────────────────────────────────────────
-- 2. Storage Policies
-- ──────────────────────────────────────────────────────────────────────────
-- Each user can only access objects where the first folder segment matches
-- their auth.uid(). This is the standard Supabase per-user isolation pattern.
-- ──────────────────────────────────────────────────────────────────────────

-- SELECT (download): users can read their own files
create policy "storage_select_own"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'user-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- INSERT (upload): users can upload to their own folder
create policy "storage_insert_own"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'user-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- UPDATE (overwrite/move): users can update their own files
create policy "storage_update_own"
  on storage.objects
  for update
  to authenticated
  using (
    bucket_id = 'user-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  )
  with check (
    bucket_id = 'user-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- DELETE: users can delete their own files
create policy "storage_delete_own"
  on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'user-files'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
